include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # 启用推荐的规则
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_final_fields
    - prefer_final_in_for_each
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_relative_imports
    - sort_child_properties_last
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_super_parameters
    
    # 禁用一些过于严格的规则
    - avoid_print: false  # 允许在开发阶段使用print
